### PR TITLE
remove zlib build from macos

### PR DESCRIPTION
**Pull request by bjia56**
This build doesn't seem to be doing anything anymore. Furthermore, zlib 1.3.1 was just released and the 1.3 source download link is now broken.

### CODE REVIEW

**Comment by yifeikong** [comment]
The build failure of docker images should be unrelated, right? It seems to be a random timeout.

If the removed step has been not working already, the system's zlib was linked?

**Comment by bjia56** [comment]
This only stopped working today because zlib 1.3 is no longer available at the specified url

**Comment by yifeikong** [comment]
I see, there is no apple silicon support anyway.

https://github.com/yifeikong/curl-impersonate/blob/fad7ca410e531b04dc2183ca41becfceccc0d8ee/.github/workflows/build-and-test-make.yml#L436-L445

**Comment by yifeikong** [comment]
I just noticed that zlib is still referenced here.

https://github.com/yifeikong/curl-impersonate/blob/ecdf1e0bcc17bb9e3b96bd2fb236549d0301c12d/.github/workflows/build-and-test-make.yml#L425-L435

Will this PR break aarch/arm build?

**Comment by bjia56** [comment]
arm/arm64 uses a different pipeline so that part is not hit on those builds

**Comment by bjia56** [comment]
Now that I think about it, I'm not certain that the macos build isn't using the custom zlib. I can revert this change and fix the zlib download url

**Comment by yifeikong** [comment]
Yes, I think it's probably better to revert it, considering we want to compile M1 biniaries in #21.

**Pull request merged**
