### PR TITLE
Bundle dependency archives in release

### PR DESCRIPTION
**Pull request by bjia56**
As discussed in https://github.com/yifeikong/curl_cffi/pull/259

### CODE REVIEW

**Comment by yifeikong** [comment]
Would you like to be a collaborator of this repository? You can merge these PRs when you see them fit. For the building and compiling parts, you are more a expert that I am.

**Comment by bjia56** [comment]
Sure, I'd be open to it. Thanks!

**Comment by bjia56** [comment]
@yifeikong ok with you if I tag a prerelease to test https://github.com/yifeikong/curl_cffi/pull/259?

**Comment by yifeikong** [comment]
Sure, please do.

**Pull request merged**
